// import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home | E-Commerce', // Replace 'E-Commerce' with the proper name of your wine-shop. This word is the main keyword for the website
    template: '%s | E-Commerce', // Replace 'E-Commerce' with the proper name of your wine-shop
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
