import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home | E-Commerce', // Replace 'E-Commerce' with the proper name of your wine-shop. This word is the main keyword for the website
    template: '%s | E-Commerce', // Replace 'E-Commerce' with the proper name of your wine-shop
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>E-Commerce</h1>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/products" data-test-id="products-link">
              Products
            </Link>{' '}
            {/* Products should be a dropdown products list when hovering*/}
            <Link href="/cart">Cart</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
